Fix incorrect error message displayed for lookup failures on a symbol starting with typeof
Prior to this changeset, the code:

    let A = typeof(B)::Z;
    let B: s32 = uninit;

would produce the error message:

    [test.sunder:1] error: use of undeclared identifier `Z`
    let A = typeof(B)::Z;
            ^

indicating that an error was on the `typeof` rather than on the
identifier `Z`. This changeset updates symbol lookup resolution so that
this error will now display correctly as:

    [test.sunder:1] error: use of undeclared identifier `Z` within `s32`
    let A = typeof(B)::Z;
                       ^